# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_activity_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('stu_class', models.CharField(max_length=20, verbose_name='班级')),
                ('stu_id', models.CharField(max_length=12, verbose_name='学号')),
                ('act_name', models.CharField(max_length=20, verbose_name='报告名称')),
                ('act_time', models.DateField(verbose_name='活动时间')),
            ],
            options={
                'verbose_name': '学术报告记录',
                'verbose_name_plural': '学术报告',
                'db_table': 'academic_report',
                'managed': False,
            },
        ),
    ]
